"""Phase 20 — routing evaluation (Objective 3: keep quality, cut work).

For every labelled query in eval_corpus.py, run the same index two ways:
  always-hybrid   mode=smart: BM25 + embedding + vector + fusion, every time
  router          mode=auto: the cheapest tier the router picks, escalating once if unsure
and compare hit@1, hit@5, MRR, latency and the stages that actually ran,
overall and per expected tier. A third pass measures the reranker alone:
hybrid vs hybrid+rerank on the multi-part queries.

Prints a Markdown table (pasted into the README) and writes
backend/data/eval_routing.json. Every number is reproducible: the corpus
and queries are generated by the script, the models are the shipped ones.

Run with:  backend/venv/bin/python backend/scripts/evaluate_routing.py
"""

import json
import os
import shutil
import statistics
import sys
import tempfile
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from eval_corpus import DOCS, QUERIES, write_corpus  # noqa: E402

from app.embeddings.model import EmbeddingModel, default_model_dir  # noqa: E402
from app.files.identity import build_file_record  # noqa: E402
from app.indexing import Indexer  # noqa: E402
from app.search import SearchService  # noqa: E402
from app.search.reranker import Reranker  # noqa: E402
from app.search.router import PLANS  # noqa: E402
from app.storage import FileRecordStore, KeywordStore, LanceDBVectorStore  # noqa: E402

MODELS = Path(__file__).resolve().parents[1] / "models"
OUT = Path(__file__).resolve().parents[1] / "data" / "eval_routing.json"
REPEATS = 3  # latency is the median of this many runs per query


def build(workdir: Path) -> SearchService:
    files = workdir / "files"
    write_corpus(files)
    model = EmbeddingModel(default_model_dir(MODELS))
    vector_store = LanceDBVectorStore(str(workdir / "vectors"))
    keyword_store = KeywordStore(workdir / "keyword.db")
    record_store = FileRecordStore(workdir / "files.db")
    indexer = Indexer(model, vector_store, keyword_store, record_store)
    for name in DOCS:
        record = build_file_record(files / name)
        record_store.upsert(record)
        indexer.index_file(files / name, record.file_id, record.hash)
    search = SearchService(model, vector_store, keyword_store, record_store)
    if (MODELS / "ms-marco-MiniLM-L-6-v2" / "model.onnx").exists():
        search.reranker = Reranker(MODELS / "ms-marco-MiniLM-L-6-v2")
    return search


def relevant_rank(results: list[dict], relevant: list[str]) -> int | None:
    names = {Path(r).name for r in relevant}
    for i, r in enumerate(results, start=1):
        if r["filename"] in names:
            return i
    return None


def run(search: SearchService, mode: str, force_plan=None) -> list[dict]:
    rows = []
    for query, relevant, expected_tier in QUERIES:
        latencies, results, route = [], None, None
        for _ in range(REPEATS):
            t0 = time.perf_counter()
            if force_plan is not None:
                from app.search.query_parsing import parse_query
                parsed = parse_query(query)
                results = search._run_plan(force_plan, parsed.text, parsed.text, parsed, search._active_records(), 10, [])
                route = {"tier": force_plan.tier, "stages": [], "escalated": False}
            else:
                results, route = search.search_routed(query, top_k=10, mode=mode)
            latencies.append((time.perf_counter() - t0) * 1000)
        rank = relevant_rank(results, relevant)
        both = len(relevant) < 2 or all(any(r["filename"] == Path(f).name for r in results[:5]) for f in relevant)
        stages_ran = [s["stage"] for s in route["stages"] if not s.get("skipped") and s["stage"] in ("keyword", "semantic", "names", "rerank")]
        rows.append({
            "query": query, "expected_tier": expected_tier, "tier": route["tier"], "escalated": route.get("escalated", False),
            "rank": rank, "hit1": rank == 1, "hit5": rank is not None and rank <= 5, "rr": 1 / rank if rank else 0.0, "both5": both,
            "ms": statistics.median(latencies), "embedded": "semantic" in stages_ran, "reranked": "rerank" in stages_ran,
        })
    return rows


def summarize(rows: list[dict]) -> dict:
    n = len(rows)
    return {
        "n": n,
        "hit@1": sum(r["hit1"] for r in rows) / n,
        "hit@5": sum(r["hit5"] for r in rows) / n,
        "MRR": sum(r["rr"] for r in rows) / n,
        "both@5": sum(r["both5"] for r in rows) / n,
        "mean_ms": sum(r["ms"] for r in rows) / n,
        "median_ms": statistics.median(r["ms"] for r in rows),
        "embedded": sum(r["embedded"] for r in rows) / n,
        "escalated": sum(r["escalated"] for r in rows) / n,
    }


def pct(x: float) -> str:
    return f"{100 * x:.0f}%"


def main() -> None:
    workdir = Path(tempfile.mkdtemp())
    try:
        search = build(workdir)
        search.search("warm up", mode="smart")  # first-call costs (model warm-up) out of the timings
        hybrid = run(search, "smart")
        router = run(search, "auto")

        print(f"\n## Routing evaluation — {len(QUERIES)} labelled queries over {len(DOCS)} generated documents (median of {REPEATS} runs)\n")
        print("| Set | n | Pipeline | hit@1 | hit@5 | MRR | both@5 | mean ms | median ms | embedded | escalated |")
        print("|---|---|---|---|---|---|---|---|---|---|---|")
        report = {"overall": {}, "per_tier": {}, "reranker": {}, "router_accuracy": {}}
        for label, rows_h, rows_r, key in [("**All**", hybrid, router, "overall")] + [
            (tier, [r for r in hybrid if r["expected_tier"] == tier], [r for r in router if r["expected_tier"] == tier], tier)
            for tier in ["filename", "metadata", "keyword", "hybrid", "hybrid+rerank"]
        ]:
            if not rows_h:
                continue
            sh, sr = summarize(rows_h), summarize(rows_r)
            target = report["overall"] if key == "overall" else report["per_tier"].setdefault(key, {})
            target["always_hybrid"], target["router"] = sh, sr
            for name, s in (("always-hybrid", sh), ("router", sr)):
                print(f"| {label} | {s['n']} | {name} | {pct(s['hit@1'])} | {pct(s['hit@5'])} | {s['MRR']:.3f} | {pct(s['both@5'])} | {s['mean_ms']:.1f} | {s['median_ms']:.1f} | {pct(s['embedded'])} | {pct(s['escalated'])} |")
        oh, orr = report["overall"]["always_hybrid"], report["overall"]["router"]
        retained = orr["MRR"] / oh["MRR"] if oh["MRR"] else 1.0
        saved = 1 - orr["mean_ms"] / oh["mean_ms"] if oh["mean_ms"] else 0.0
        print(f"\n**Router keeps {pct(retained)} of always-hybrid's MRR at {pct(1 - saved)} of its mean latency ({pct(saved)} saved); "
              f"the embedding model ran for {pct(orr['embedded'])} of queries instead of {pct(oh['embedded'])}.**")
        report["overall"]["mrr_retained"], report["overall"]["latency_saved"] = retained, saved

        # Router accuracy: did it pick the tier the query was labelled with?
        sum(1 for r in router if r["tier"] == r["expected_tier"] or (r["escalated"] and r["tier"] in PLANS))
        chosen = sum(1 for r in router if r["tier"] == r["expected_tier"])
        print(f"\nRouter picked the labelled tier for {chosen}/{len(router)} queries; " + f"{sum(r['escalated'] for r in router)} escalated.")
        report["router_accuracy"] = {"matched_tier": chosen, "n": len(router), "escalated": sum(r["escalated"] for r in router)}
        mismatches = [(r["query"], r["expected_tier"], r["tier"], r["escalated"]) for r in router if r["tier"] != r["expected_tier"]]
        for q, e, g, esc in mismatches:
            print(f"  - {q!r}: expected {e}, got {g}{' (escalated)' if esc else ''}")

        # Reranker alone, on the multi-part queries: hybrid vs hybrid+rerank
        multi = [q for q in QUERIES if q[0].rstrip("?").count(", ") + q[0].count(" and ") >= 1 and q[0].endswith("?")]  # the multi-part questions
        if search.reranker is not None:
            saved_queries = QUERIES[:]
            QUERIES[:] = multi
            plain = run(search, "smart", force_plan=PLANS["hybrid"])
            reranked = run(search, "smart", force_plan=PLANS["hybrid+rerank"])
            QUERIES[:] = saved_queries
            sp, sr2 = summarize(plain), summarize(reranked)
            report["reranker"] = {"hybrid": sp, "hybrid+rerank": sr2}
            print(f"\n## Reranker on the {len(multi)} multi-part queries\n")
            print("| Pipeline | hit@1 | hit@5 | MRR | both@5 | mean ms |")
            print("|---|---|---|---|---|---|")
            for name, s in (("hybrid", sp), ("hybrid + rerank (promotion)", sr2)):
                print(f"| {name} | {pct(s['hit@1'])} | {pct(s['hit@5'])} | {s['MRR']:.3f} | {pct(s['both@5'])} | {s['mean_ms']:.1f} |")

        misses = [(r["query"], r["tier"], r["rank"]) for r in router if not r["hit5"]]
        if misses:
            print("\nRouter misses (not in top 5):")
            for q, t, rk in misses:
                print(f"  - {q!r} via {t}: rank {rk}")
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(json.dumps({"report": report, "hybrid": hybrid, "router": router}, indent=2))
        print(f"\nWritten to {OUT}")
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    main()
    sys.stdout.flush()
    os._exit(0)  # success path only: skip native teardown — onnxruntime/LanceDB worker threads once raced the C++ static destructors at exit ("recursive_mutex lock failed", run_all_phases 2026-09-21) after every result was written
