/** Tokens from `Frontend Design/intellifile_obsidian/DESIGN.md` (IntelliFile Obsidian). */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#11131b",
        "surface-dim": "#11131b",
        "surface-bright": "#373942",
        "surface-container-lowest": "#0c0e16",
        "surface-container-low": "#191b24",
        "surface-container": "#1d1f28",
        "surface-container-high": "#282a32",
        "surface-container-highest": "#33343d",
        "on-surface": "#e2e1ed",
        "on-surface-variant": "#bbcac6",
        outline: "#859491",
        "outline-variant": "#3c4947",
        primary: "#a3fff3",
        "primary-container": "#5ee7d8",
        "on-primary": "#003732",
        "on-primary-container": "#00665d",
        "primary-fixed-dim": "#4fdbcc",
        secondary: "#b4c5ff",
        "secondary-container": "#163f9e",
        "on-secondary-container": "#9bb2ff",
        error: "#ffb4ab",
        "error-container": "#93000a",
        canvas: "#0f1119",
        shell: "#121520",
        content: "#151824",
        overlay: "#1a1e2e",
        accent: "#5ee7d8",
        accent2: "#7c9cff",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: { DEFAULT: "0.5rem", md: "0.75rem", lg: "1rem", xl: "1.5rem" },
      boxShadow: {
        glow: "0 0 16px rgba(94, 231, 216, 0.15)",
        palette: "0 24px 48px -12px rgba(0,0,0,0.7), 0 0 0 1px rgba(124,156,255,0.15)",
      },
      keyframes: {
        rise: { from: { opacity: 0, transform: "translateY(6px)" }, to: { opacity: 1, transform: "none" } },
        shimmer: { from: { backgroundPosition: "200% 0" }, to: { backgroundPosition: "-200% 0" } },
        pulse2: { "0%": { opacity: 0.8, transform: "scale(1)" }, "100%": { opacity: 0, transform: "scale(1.8)" } },
        bar: { "0%,100%": { height: "4px" }, "50%": { height: "16px" } },
        sweep: { to: { "--a": "360deg" } },
        dot: { "0%,80%,100%": { opacity: 0.25, transform: "translateY(0)" }, "40%": { opacity: 1, transform: "translateY(-3px)" } },
        flash: { "0%": { backgroundColor: "rgba(94,231,216,0.6)" }, "100%": { backgroundColor: "rgba(94,231,216,0.22)" } },
      },
      animation: {
        rise: "rise .35s cubic-bezier(.2,.8,.2,1) forwards",
        shimmer: "shimmer 1.2s ease-in-out infinite",
        pulse2: "pulse2 1.4s ease-out infinite",
        bar: "bar .9s ease-in-out infinite",
        dot: "dot 1.2s infinite",
        flash: "flash 1.2s ease-out .3s 1",
      },
    },
  },
  plugins: [],
};
